/*
  Warnings:

  - The values [SERVICIOS,PRODUCTOS,CONSULTORIA,OTRO] on the enum `Giro` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "Giro_new" AS ENUM ('EMPRESA_PROFESIONAL_PERFIL', 'EMPRESA_APARATOLOGIA_PERFIL', 'EMPRESA_MOBILIARIO_PERFIL', 'EMPRESA_DESECHABLES_PERFIL', 'EMPRESA_AROMATERAPIA_PERFIL', 'EMPRESA_FABRICANTE_LABORATORIO_PERFIL', 'EMPRESA_ADMINISTRACION_PERFIL', 'SOCIEDAD_ASOCIACION_PERFIL', 'UNIVERSIDAD_ESCUELA_PERFIL', 'OTRO_PERFIL');
ALTER TABLE "Empresa" ALTER COLUMN "giro" DROP DEFAULT;
ALTER TABLE "Empresa" ALTER COLUMN "giro" TYPE "Giro_new" USING ("giro"::text::"Giro_new");
ALTER TYPE "Giro" RENAME TO "Giro_old";
ALTER TYPE "Giro_new" RENAME TO "Giro";
DROP TYPE "Giro_old";
ALTER TABLE "Empresa" ALTER COLUMN "giro" SET DEFAULT 'EMPRESA_PROFESIONAL_PERFIL';
COMMIT;

-- AlterTable
ALTER TABLE "Empresa" ALTER COLUMN "giro" SET DEFAULT 'EMPRESA_PROFESIONAL_PERFIL';
